### ISSUE TITLE
all specs failing with 404 error.

### ISSUE THREAD

**Issue by mwlang** [kjakub/rapportive#1]
I just installed this gem, but it doesn't seem to work at all.

switched to the gem folder and ran specs with rspec and get the following:

```
D, [2015-11-12T14:15:52.891248 #45404] DEBUG -- : HTTPI GET request to rapportive.com (httpclient)
FD, [2015-11-12T14:15:53.770723 #45404] DEBUG -- : HTTPI GET request to rapportive.com (httpclient)
FD, [2015-11-12T14:15:53.903127 #45404] DEBUG -- : HTTPI GET request to rapportive.com (httpclient)
F

Failures:

  1) Rapportive::Search should create a new Rapportive client with a valid token
     Failure/Error: client = Rapportive::Search.new
     JSON::ParserError:
       757: unexpected token at '<html>
       <head><title>404 Not Found</title></head>
       <body bgcolor="white">
       <center><h1>404 Not Found</h1></center>
       <hr><center>nginx</center>
       </body>
       </html>
       '
     # /Users/mwlang/.rvm/gems/ruby-2.1.5/gems/json-1.8.3/lib/json/common.rb:155:in `parse'
     # /Users/mwlang/.rvm/gems/ruby-2.1.5/gems/json-1.8.3/lib/json/common.rb:155:in `parse'
     # ./lib/rapportive.rb:14:in `initialize'
     # ./spec/rapportive_spec.rb:4:in `new'
     # ./spec/rapportive_spec.rb:4:in `block (2 levels) in <top (required)>'

  2) Rapportive::Search should search for an email
     Failure/Error: client = Rapportive::Search.new
     JSON::ParserError:
       757: unexpected token at '<html>
       <head><title>404 Not Found</title></head>
       <body bgcolor="white">
       <center><h1>404 Not Found</h1></center>
       <hr><center>nginx</center>
       </body>
       </html>
       '
     # /Users/mwlang/.rvm/gems/ruby-2.1.5/gems/json-1.8.3/lib/json/common.rb:155:in `parse'
     # /Users/mwlang/.rvm/gems/ruby-2.1.5/gems/json-1.8.3/lib/json/common.rb:155:in `parse'
     # ./lib/rapportive.rb:14:in `initialize'
     # ./spec/rapportive_spec.rb:10:in `new'
     # ./spec/rapportive_spec.rb:10:in `block (2 levels) in <top (required)>'

  3) Rapportive::Search should return no result for a not valid email
     Failure/Error: client = Rapportive::Search.new
     JSON::ParserError:
       757: unexpected token at '<html>
       <head><title>404 Not Found</title></head>
       <body bgcolor="white">
       <center><h1>404 Not Found</h1></center>
       <hr><center>nginx</center>
       </body>
       </html>
       '
     # /Users/mwlang/.rvm/gems/ruby-2.1.5/gems/json-1.8.3/lib/json/common.rb:155:in `parse'
     # /Users/mwlang/.rvm/gems/ruby-2.1.5/gems/json-1.8.3/lib/json/common.rb:155:in `parse'
     # ./lib/rapportive.rb:14:in `initialize'
     # ./spec/rapportive_spec.rb:22:in `new'
     # ./spec/rapportive_spec.rb:22:in `block (2 levels) in <top (required)>'

Finished in 1.42 seconds (files took 0.28549 seconds to load)
3 examples, 3 failures

Failed examples:

rspec ./spec/rapportive_spec.rb:3 # Rapportive::Search should create a new Rapportive client with a valid token
rspec ./spec/rapportive_spec.rb:9 # Rapportive::Search should search for an email
rspec ./spec/rapportive_spec.rb:21 # Rapportive::Search should return no result for a not valid email
```

**Comment by kjakub** [comment]
Hi Michael, 

thank you for interest. But even it looks like that those failing specs coming from code itself i have to tell that as far as i know rapportive changed policy and approach of rotating emails for obtaining new session to communicate with rapportive api no more works. Thus i stop maintaining this gem. However if you are still interested to use rapportive somehow we can work on something new..
